# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: "pdo_%database.driver%"
                host: "%database.host%"
                port: "%database.port%"
                dbname: "%database.name%"
                user: "%database.user%"
                password: "%database.password%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    # Remove when we don't have legacy tables anymore
                    enum: string
        types:
            seo_follow: App\Domain\Meta\SEOFollowDBALType
            seo_index: App\Domain\Meta\SEOIndexDBALType
            locale: Common\Doctrine\Type\LocaleType
            datetime: Common\Doctrine\Type\UTCDateTimeType
            datetimetz: Common\Doctrine\Type\UTCDateTimeType
            time: Common\Doctrine\Type\UTCTimeType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    common:
                        type: annotation
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Common/Doctrine/Entity"
                        alias: Common
                        prefix: Common\Doctrine\Entity

doctrine_orm_bridge:
    entity_manager: default
    connection: default

services:
    fork.doctrine.entity_schema:
        class: App\Service\Doctrine\EntitySchema
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    # @todo: remove this service in the next major release.
    fork.entity.create_schema:
        class: Common\Doctrine\Entity\CreateSchema
        deprecated: 'The "%service_id%" service is deprecated. Use "fork.entity_schema" instead'
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    fork.repository.meta:
        class: App\Domain\Meta\MetaRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App\Domain\Meta\Meta
