services:
    fork.datepicker.form:
        class: App\Form\Type\DatePickerType
        arguments:
          - "@service_container"
        tags:
          - { name: form.type }
    form.type.editor:
        class: App\Form\Type\Backend\EditorType
        tags:
            - { name: form.type, alias: editor}
    form.type.meta:
        class: App\Form\Type\Backend\MetaType
        arguments:
            - "@fork.repository.meta"
            - "@translator"
        tags:
            - { name: form.type, alias: meta}
